### ISSUE TITLE
add simplePrint option to tei p5 framework

### ISSUE THREAD

**Issue by lb42** [TEIC/oxygen-tei#13]
It should  be possible to create and validate TEI simplePrint documents in  oxygen when the schema is released. There's a sample file and a template file in the exemplars directory which çan  be used, and the schemas can be generated from the odd in the same way as other  exemplars. Council has already agreed that this should be done as part of next release.

**Comment by martindholmes** [comment]
Is it now simpleText? It was simplePrint yesterday.

**Comment by lb42** [comment]
Sorry, my bad. simplePrint it is. Typing on a tablet is always a challenge.

**Comment by martindholmes** [comment]
@lb42: It's "in" the bleeding edge plugin already, since it's an Exemplar, but it points at a schema here:

http://www.tei-c.org/release/xml/tei/custom/schema/relaxng/tei_simplePrint.rng

which won't exist until after the next release. But are there any particular transformation scenarios that should be associated with it? Should it have an accompanying Author Mode stylesheet? Are there any particular custom editing actions that it needs? If none of the above, then I guess we're done.

**Comment by lb42** [comment]
Nope, not yet. No doubt in the fullness of time...

**Comment by martindholmes** [comment]
I think this is completed for the moment; when the Stylesheets have nifty processing pipelines for simplePrint docs, we can add matching scenarios to the plugin.
