### ISSUE TITLE
oXygen ImageMap Editor actions missing

### ISSUE THREAD

**Issue by bwbohl** [TEIC/oxygen-tei#43]
Since v18 oXygen XML Editor ships with integrated imageMap Editor functionality (cf. https://www.oxygenxml.com/doc/versions/18/ug-editor/topics/image-map-tei.html). The corresponding Author Actions are available form the TEI framework shipping with oXygen; unfortunately the are missing from the framework maintained in this repo.

**Comment by AlexJitianu** [comment]
Those actions use a new API that was introduced in Oxygen version 18. The TEI framework built in this repository wants to maintain a compatibility with older versions of Oxygen. At that time it was 15.2+, and committing those actions would have led to exceptions in those older version, as the required API was missing.

Looking inside https://tei-c.org/release/oxygen/updateSite.oxygen , I see that the compatible version is now 18.0+. This  means that I could merge the operations as well as maybe other TEI extensions that are present in Oxygen v18 TEI framework and not present in this framework.

**Comment by martindholmes** [comment]
@AlexJitianu Please go ahead and do that. We decided that it's not practical or beneficial to try to maintain backwards compatibility indefinitely.

**Comment by bwbohl** [comment]
any progress on this?

**Comment by AlexJitianu** [comment]
Hi,

1. I've integrated Oxygen 18.1 resources into a new branch: https://github.com/TEIC/oxygen-tei/tree/oxygen_18_update
1. After we test it internally to make sure everything it's O.K., I will make a _Pull request_. 
1. Although the add-on says the compatible version is 18.0+, I chose to update to Oxygen 18.1 because anyone using 18.0 has the legal right to use 18.1 and there's no point in missing out on the new features added in version 18.1. I hope TEIC will agree to change the compatible version to 18.1+

**Comment by bwbohl** [comment]
great news, I will try it, too!

**Comment by martindholmes** [comment]
Thanks Alex! Absolutely fine with 18.1.

**Comment by martindholmes** [comment]
@AlexJitianu I've merged the pull request, but our build is now showing lots of instances of this error:

    [javac] /var/lib/jenkins/jobs/oxygen-tei-stable/workspace/oxygen-tei/frameworks/tei/src/ro/sync/ecss/extensions/commons/AbstractDocumentTypeHelper.java:53: error: package ro.sync.annotations.api does not exist
    [javac] import ro.sync.annotations.api.API;
    [javac]            

What do we need to fix?

**Comment by AlexJitianu** [comment]
@martindholmes , it is an additional jar file, `oxygen-annotations-18.1.0.3.jar`. In my Jenkins build I get these jars like this:

```
wget --no-check-certificate -O lib/oxygen.jar https://www.oxygenxml.com/maven/com/oxygenxml/oxygen/18.1.0.3/oxygen-18.1.0.3.jar
wget --no-check-certificate -O lib/oxygen-annotations.jar https://www.oxygenxml.com/maven/com/oxygenxml/oxygen-annotations/18.1.0.3/oxygen-annotations-18.1.0.3.jar
```

**Comment by martindholmes** [comment]
@AlexJitianu If we go the same route, we'll have to update the build every time the versions of those files change, won't we? Is there a more robust way to do this?

**Comment by AlexJitianu** [comment]
@martindholmes Right now you commit oxygen.jar inside the git project itself. It's still an additional step. It is recommended to take these jars from our Maven repository instead of making copies into the project.
We could make this a Maven project and the dependencies will be downloaded automatically, but perhaps we should add a new issue for this.

**Comment by martindholmes** [comment]
@AlexJitianu The way I've rewritten it, those jars are pulled from the maven repo manually. I guess we would only have to change those version numbers if/when we decide to move our old-version-support forward to a more recent version, which would be a conscious decision, so that should be fine. I should probably remove the old oxygen.jar from the repo entirely, but I'll wait till after today's release.

**Comment by AlexJitianu** [comment]
@martindholmes , I think you forgot to remove `oxygen.jar` form the lib folder. While you're at it, I believe you can also remove `apiSrc.zip`. It was added there in the beginning, before we began publishing our SDK on Maven and it looks like it was never updated.

**Comment by martindholmes** [comment]
Should be done now.

**Comment by martindholmes** [comment]
I think this can be closed now.
